var pem_file = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvPMZfK20ln1zzbdJTDHo
Xu5N1wuYfdZ6MFHQl0MODI4CHLFaANjyuGNxR1p6ncGmbzDqdzOmJ/SnjbOX6NEr
oZIORziCQgzz6RFyDDT1R35rHR6hWnhCw5LKaEZIy7XN6xVLjdM8Pin9iFzAZuiH
l7OYL5sOFjhvbzC0RG8mwQEsg0yaeEXtyqYSDsuXTrQJlLAWDcQuVarAJeuYVFGJ
gz89F+ev0/umkKRSdldGde/n8MxTffC6e0xRgWjLAugHWBSh4Dd/VqHEqbdDrOhe
Ef/YFZR4cY/5OvNghl/HJGJpigpl3wW4hjXtCDtmA0IFOAN+pH+pTNHC52gbFweK
RQIDAQAB
-----END PUBLIC KEY-----`